In [1]:
import numpy as np

a = np.array([1,2,3])

a

array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [5]:
np.shape(a)

(3,)

In [6]:
a[1]

2

In [7]:
b = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
             ])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b.shape

(3, 3)

In [11]:
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
d = np.ones((4, 2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
f = np.full((5, 2), 7)
f

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
g = b[1:, 1:]
g

array([[5, 6],
       [8, 9]])

In [16]:
g2 = b[:2 , :2]
g2

array([[1, 2],
       [4, 5]])

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
g[1, 1]

9

In [19]:
g[1,1] = 2021
g

array([[   5,    6],
       [   8, 2021]])

In [20]:
b

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,    8, 2021]])

In [21]:
b[1,1] = 5050

In [22]:
g

array([[5050,    6],
       [   8, 2021]])

In [25]:
x = np.array([
    [1,2],
    [3,4]
],
dtype = np.float64)
y = np.array([
    [5,6],
    [7,8]
],
dtype = np.float64)
print('La matrix x es: \n', x)
print('La matrix y es: \n', y)

La matrix x es: 
 [[1. 2.]
 [3. 4.]]
La matrix y es: 
 [[5. 6.]
 [7. 8.]]


In [26]:
print('sum of matrix \n{} y \n{} is : \n {}'.format(x, y, x+y))

sum of matrix 
[[1. 2.]
 [3. 4.]] y 
[[5. 6.]
 [7. 8.]] is : 



In [27]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [28]:
comp = x+y = np.add(x,y)
comp

SyntaxError: can't assign to operator (<ipython-input-28-c522706cda75>, line 1)

In [29]:
print(np.array_equal(x+y, np.add(x,y)))


True


In [30]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [32]:
print(np.array_equal(x-y, np.subtract(x,y)))

True


In [33]:
print(np.array_equal(x*y, np.multiply(x,y)))

True


In [34]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [35]:
np.sum(x, axis = 1)

array([3., 7.])

In [36]:
x

array([[1., 2.],
       [3., 4.]])

In [37]:
np.sum(x, axis = 0)

array([4., 6.])